// This file will be generated by Supabase CLI
// Run: npm run db:generate-types
// For now, we'll add placeholder types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be defined here after running db:generate-types
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

